description: "TDS Virtual TA Project - 15 Realistic Evaluation Questions (Fixed)"

providers:
  - id: openai:gpt-4o-mini
    config:
      apiKey: env:MY_OPENAI_KEY

  - id: https://virtual-ta-discourse-responder.onrender.com/api
    config:
      method: POST
      headers:
        Content-Type: application/json
      body:
        question: "{{vars.question}}"
      responseParser: |
        const response = JSON.parse(output);
        return response.answer;

prompts:
  - "{{vars.question}}"

defaultTest:
  assert:
    - type: javascript
      value: |
        if (typeof output !== 'string' || output.length < 10) {
          return { pass: false, score: 0, reason: 'Response too short or invalid' };
        }
        try {
          if (output.startsWith('{')) {
            const response = JSON.parse(output);
            if (!response.answer || !Array.isArray(response.links)) {
              return { pass: false, score: 0, reason: 'Invalid response structure' };
            }
            return { pass: true, score: 1 };
          }
        } catch(e) {}
        return { pass: true, score: 1 };

tests:
  - vars:
      question: "What is 2+2?"
    assert:
      - type: contains
        value: "4"

outputPath: ./evaluation_results.json
writeLatestResults: true

cache:
  enabled: true

commandLineOptions:
  verbose: true
