description: "TDS Virtual TA Project - Final Working Configuration"

providers:
  - id: openai:gpt-4o-mini
    config:
      apiKey: env:MY_OPENAI_KEY
  - id: https://virtual-ta-discourse-responder.onrender.com/api
    config:
      method: POST
      headers:
        Content-Type: application/json
      body:
        question: "{{vars.question}}"
      transformResponse: |
        try {
          const response = JSON.parse(output);
          return response.answer || output;
        } catch (e) {
          return output;
        }

prompts:
  - "{{vars.question}}"

tests:
  - vars:
      question: "The question asks to use gpt-3.5-turbo-0125 model but the ai-proxy provided by Anand sir only supports gpt-4o-mini. So should we just use gpt-4o-mini or use the OpenAI API for gpt3.5 turbo?"
    assert:
      - type: contains
        value: "gpt-3.5-turbo-0125"
      - type: contains
        value: "https://discourse.onlinedegree.iitm.ac.in/t/ga5-question-8-clarification/155939"

outputPath: ./evaluation_results.json
writeLatestResults: true
