description: "TDS Virtual TA Project - Working Configuration"
providers:
  - id: openai:gpt-4o-mini
    config:
      apiKey: env:MY_OPENAI_KEY
  - id: https://virtual-ta-discourse-responder.onrender.com/api
    config:
      method: POST
      headers:
        Content-Type: application/json
      body:
        question: "{{vars.question}}"
      responseParser: "JSON.parse(output).answer"

prompts:
  - "{{vars.question}}"

tests:
  - vars:
      question: "The question asks to use gpt-3.5-turbo-0125 model but the ai-proxy provided by Anand sir only supports gpt-4o-mini. So should we just use gpt-4o-mini or use the OpenAI API for gpt3.5 turbo?"
    assert:
      - type: contains
        value: "gpt-3.5-turbo-0125"

outputPath: ./evaluation_results.json
writeLatestResults: true
