description: "TDS Virtual TA Project - 15 Realistic Evaluation Questions"

providers:
  - id: openai:gpt-4o-mini
    config:
      apiKey: env:OPENAI_API_KEY

  # Fixed: Use 'http' provider type instead of custom name
  - id: http://virtual-ta-api
    config:
      url: https://virtual-ta-discourse-responder.onrender.com/api
      method: POST
      headers:
        Content-Type: application/json
      body:
        question: "{{question}}"
      responseParser: |
        // Handle both string and JSON responses
        if (typeof output === 'string') {
          try {
            const parsed = JSON.parse(output);
            return parsed.answer || parsed.response || output;
          } catch (e) {
            return output;
          }
        }
        return output.answer || output.response || output;

prompts:
  - "{{question}}"

defaultTest:
  assert:
    - type: javascript
      value: |
        if (typeof output !== 'string' || output.length < 10) {
          return { pass: false, score: 0, reason: 'Response too short or invalid' };
        }
        
        // Check if response contains meaningful content
        const meaningfulWords = output.split(/\s+/).filter(word => word.length > 3).length;
        if (meaningfulWords < 5) {
          return { pass: false, score: 0.3, reason: 'Response lacks meaningful content' };
        }
        
        return { pass: true, score: 1 };

tests:
  - vars:
      question: "The question asks to use gpt-3.5-turbo-0125 model but the ai-proxy provided by Anand sir only supports gpt-4o-mini. So should we just use gpt-4o-mini or use the OpenAI API for gpt3.5 turbo?"
    assert:
      - type: llm-rubric
        value: "Response should clarify to use gpt-3.5-turbo-0125 not gpt-4o-mini, and suggest using OpenAI API directly"
      - type: contains
        value: "gpt-3.5-turbo-0125"
      - type: contains
        value: "https://discourse.onlinedegree.iitm.ac.in/t/ga5-question-8-clarification/155939"

  - vars:
      question: "If a student scores 10/10 on GA4 as well as a bonus, how would it appear on the dashboard?"
    assert:
      - type: llm-rubric
        value: "Response should mention the dashboard showing 110 or 110%"
      - type: contains
        value: "110"
      - type: contains
        value: "https://discourse.onlinedegree.iitm.ac.in/t/ga4-data-sourcing-discussion-thread-tds-jan-2025/165959"

  - vars:
      question: "I know Docker but have not used Podman before. Should I use Docker for this course?"
    assert:
      - type: llm-rubric
        value: "Response should recommend Podman for the TDS course"
      - type: llm-rubric
        value: "Response can mention Docker is acceptable"
      - type: contains
        value: "Podman"
      - type: contains
        value: "https://tds.s-anand.net/#/docker"

  - vars:
      question: "When is the TDS Sep 2025 end-term exam?"
    assert:
      - type: llm-rubric
        value: "Response should indicate information is not available or unknown"
      - type: contains
        value: "don't"

  - vars:
      question: "Has the Project 1 deadline been extended? I see conflicting dates in different announcements."
    assert:
      - type: llm-rubric
        value: "Response should mention deadline extension to 16 Feb 2025"
      - type: contains
        value: "16 Feb 2025"

  - vars:
      question: "My TDS assignment is not submitting through the portal. I keep getting an error. What should I do?"
    assert:
      - type: llm-rubric
        value: "Response should provide troubleshooting steps"
      - type: contains
        value: "browser"

  # Add more test cases for better coverage
  - vars:
      question: "How do I set up the development environment for TDS projects?"
    assert:
      - type: llm-rubric
        value: "Response should mention Python, virtual environment, or required packages"
      - type: contains-any
        value: ["Python", "pip", "virtual", "environment"]

  - vars:
      question: "What are the submission requirements for TDS projects?"
    assert:
      - type: llm-rubric
        value: "Response should mention GitHub repository, README, or specific submission format"
      - type: contains-any
        value: ["GitHub", "repository", "README", "submission"]

  - vars:
      question: "I'm getting import errors when running the TDS starter code. How do I fix this?"
    assert:
      - type: llm-rubric
        value: "Response should provide troubleshooting steps for import issues"
      - type: contains-any
        value: ["install", "pip", "requirements", "dependencies"]

  - vars:
      question: "What's the difference between GA and Project submissions in TDS?"
    assert:
      - type: llm-rubric
        value: "Response should explain the distinction between graded assignments and projects"
      - type: contains-any
        value: ["GA", "project", "assignment", "graded"]

  - vars:
      question: "When running the llm embed command, I'm getting 'insufficient_quota' error but I've only used the model 2-3 times. How do I increase my quota?"
    assert:
      - type: llm-rubric
        value: "Response should mention quota management or API key issues"
      - type: contains
        value: "quota"

  - vars:
      question: "I'm finding TDS too difficult at my current level. Should I drop this course and take it in a later term?"
    assert:
      - type: llm-rubric
        value: "Response should mention GA1 prerequisite or suggest getting help first"
      - type: contains
        value: "GA1"

  - vars:
      question: "For Project 1, do I need to make my GitHub repository public? And what should I include in the LICENSE file?"
    assert:
      - type: llm-rubric
        value: "Response should mention public repository and MIT license"
      - type: contains
        value: "public"

  - vars:
      question: "I'm getting an error for the Vector Databases question worth 1 mark in GA3. The validation seems to be failing even though my answer looks correct."
    assert:
      - type: llm-rubric
        value: "Response should address GA3 or vector database validation issues"
      - type: contains
        value: "GA3"

  - vars:
      question: "Where can I find the recorded sessions for TDS? I missed the live session on 10th May."
    assert:
      - type: llm-rubric
        value: "Response should mention YouTube playlist or course materials"
      - type: contains
        value: "YouTube"

outputPath: ./evaluation_results.json
writeLatestResults: true

cache:
  enabled: true

commandLineOptions:
  verbose: true
